logging:
  level:
    com.g.mds: debug

spring:
  datasource-master:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/next?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: MYSQL_ROOT_PASSWORD
    platform: mysql
    idle-timeout: 10000
    maximum-pool-size: 4
    minimum-idle: 2
    pool-name: MasterHikariPool
  datasource-slave:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/next?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: MYSQL_ROOT_PASSWORD
    platform: mysql
    idle-timeout: 10000
    maximum-pool-size: 4
    minimum-idle: 2
    pool-name: SlaveHikariPool
