// Generated 2021年1月19日 上午11:12:12 by Hibernate Tools 6.0.0.Alpha2

package com.g.mds;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * SysRoles generated by hbm2java
 */
@Data
@Entity
@Table(name = "sys_roles")
public class SysRole implements java.io.Serializable {
    @Id
    private Long id;
    private String name;
    private String status;
}


